"""
Thread dump parser for JVM thread dumps.

Parses thread dump text files generated by jstack, jcmd, kill -3, or thread dump buttons.
Supports standard Java thread dump format.
"""

import re
from typing import List, Optional, Dict
from ..models.evidence import ThreadInfo, ThreadState, LockInfo


class ThreadDumpParser:
    """
    Parser for JVM thread dump text files.

    Extracts thread information including:
    - Thread name, ID, and state
    - Stack traces
    - Lock information (held and waiting)
    - Thread priorities and daemon status
    """

    # Regex patterns for thread dump parsing
    THREAD_HEADER_PATTERN = re.compile(
        r'"([^"]+)"\s+.*?tid=(0x[0-9a-f]+|[0-9]+).*?(?:prio=(\d+))?.*?\[(.*?)\]'
    )

    # Alternative thread header format
    THREAD_HEADER_ALT = re.compile(
        r'"([^"]+)".*?#(\d+).*?(?:prio=(\d+))?.*?(?:os_prio=\d+)?.*?tid=(0x[0-9a-f]+)'
    )

    JAVA_THREAD_PATTERN = re.compile(r'"([^"]+)".*?tid=(0x[0-9a-f]+)')

    STATE_PATTERN = re.compile(r'java\.lang\.Thread\.State:\s+(\w+)')

    LOCK_WAITING_PATTERN = re.compile(
        r'- waiting (?:to lock|on) <(0x[0-9a-f]+)>\s+\(a\s+([^\)]+)\)'
    )

    LOCK_HELD_PATTERN = re.compile(
        r'- locked <(0x[0-9a-f]+)>\s+\(a\s+([^\)]+)\)'
    )

    LOCK_PARKING_PATTERN = re.compile(
        r'- parking to wait for\s+<(0x[0-9a-f]+)>\s+\(a\s+([^\)]+)\)'
    )

    def __init__(self):
        self.threads: List[ThreadInfo] = []
        self.raw_text: str = ""

    def parse_file(self, file_path: str) -> List[ThreadInfo]:
        """
        Parse a thread dump file and return list of ThreadInfo objects.

        Args:
            file_path: Path to thread dump text file

        Returns:
            List of ThreadInfo objects
        """
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            self.raw_text = f.read()

        return self.parse_text(self.raw_text)

    def parse_text(self, text: str) -> List[ThreadInfo]:
        """
        Parse thread dump text and return list of ThreadInfo objects.

        Args:
            text: Thread dump text content

        Returns:
            List of ThreadInfo objects
        """
        self.raw_text = text
        self.threads = []

        # Split into individual thread sections
        thread_sections = self._split_thread_sections(text)

        for section in thread_sections:
            thread = self._parse_thread_section(section)
            if thread:
                self.threads.append(thread)

        return self.threads

    def _split_thread_sections(self, text: str) -> List[str]:
        """Split text into individual thread sections."""
        sections = []
        current_section = []

        for line in text.split('\n'):
            # Check if this is a thread header line
            if line.startswith('"') and ('tid=' in line or '#' in line):
                # Save previous section
                if current_section:
                    sections.append('\n'.join(current_section))
                current_section = [line]
            elif current_section:
                current_section.append(line)

        # Add last section
        if current_section:
            sections.append('\n'.join(current_section))

        return sections

    def _parse_thread_section(self, section: str) -> Optional[ThreadInfo]:
        """Parse a single thread section."""
        lines = section.split('\n')
        if not lines:
            return None

        header_line = lines[0]

        # Extract thread name and ID
        match = self.THREAD_HEADER_PATTERN.search(header_line)
        if not match:
            match = self.THREAD_HEADER_ALT.search(header_line)
        if not match:
            match = self.JAVA_THREAD_PATTERN.search(header_line)

        if not match:
            return None

        thread_name = match.group(1)
        thread_id = match.group(2)

        # Extract priority if available
        priority = 5
        if len(match.groups()) >= 3 and match.group(3):
            try:
                priority = int(match.group(3))
            except (ValueError, IndexError):
                pass

        # Check daemon status
        daemon = 'daemon' in header_line.lower()

        # Extract thread state
        state = self._extract_state(section)

        # Extract stack trace
        stack_trace = self._extract_stack_trace(lines)

        # Extract lock information
        waiting_on_lock = self._extract_waiting_lock(section)
        holding_locks = self._extract_held_locks(section)

        # Check if native
        native = 'in native' in section.lower()

        return ThreadInfo(
            name=thread_name,
            thread_id=thread_id,
            state=state,
            stack_trace=stack_trace,
            waiting_on_lock=waiting_on_lock,
            holding_locks=holding_locks,
            native=native,
            daemon=daemon,
            priority=priority
        )

    def _extract_state(self, section: str) -> ThreadState:
        """Extract thread state from section."""
        match = self.STATE_PATTERN.search(section)
        if match:
            state_str = match.group(1).upper()
            try:
                return ThreadState[state_str]
            except KeyError:
                pass

        # Fallback: check header line
        if 'runnable' in section.lower():
            return ThreadState.RUNNABLE
        elif 'blocked' in section.lower():
            return ThreadState.BLOCKED
        elif 'waiting' in section.lower():
            return ThreadState.WAITING
        elif 'timed_waiting' in section.lower():
            return ThreadState.TIMED_WAITING

        return ThreadState.UNKNOWN

    def _extract_stack_trace(self, lines: List[str]) -> List[str]:
        """Extract stack trace frames."""
        stack = []
        for line in lines[1:]:  # Skip header
            stripped = line.strip()
            if stripped.startswith('at '):
                # Remove 'at ' prefix
                frame = stripped[3:].strip()
                stack.append(frame)
            elif not stripped or stripped.startswith('-'):
                # Skip empty lines and lock lines
                continue
            elif stripped.startswith('java.lang.Thread.State:'):
                # Skip state line
                continue

        return stack

    def _extract_waiting_lock(self, section: str) -> Optional[LockInfo]:
        """Extract the lock this thread is waiting on."""
        # Check for "waiting to lock" pattern
        match = self.LOCK_WAITING_PATTERN.search(section)
        if match:
            lock_id = match.group(1)
            lock_class = match.group(2)
            return LockInfo(lock_id=lock_id, lock_class=lock_class)

        # Check for "parking to wait for" pattern
        match = self.LOCK_PARKING_PATTERN.search(section)
        if match:
            lock_id = match.group(1)
            lock_class = match.group(2)
            return LockInfo(lock_id=lock_id, lock_class=lock_class)

        return None

    def _extract_held_locks(self, section: str) -> List[LockInfo]:
        """Extract locks held by this thread."""
        locks = []
        for match in self.LOCK_HELD_PATTERN.finditer(section):
            lock_id = match.group(1)
            lock_class = match.group(2)
            locks.append(LockInfo(lock_id=lock_id, lock_class=lock_class))
        return locks

    def get_thread_state_distribution(self) -> Dict[str, int]:
        """Get distribution of thread states."""
        distribution = {}
        for thread in self.threads:
            state = thread.state.value
            distribution[state] = distribution.get(state, 0) + 1
        return distribution

    def get_threads_by_state(self, state: ThreadState) -> List[ThreadInfo]:
        """Get all threads in a specific state."""
        return [t for t in self.threads if t.state == state]

    def find_thread_by_name(self, name: str) -> Optional[ThreadInfo]:
        """Find a thread by name."""
        for thread in self.threads:
            if thread.name == name:
                return thread
        return None

    def find_threads_waiting_on_lock(self, lock_id: str) -> List[ThreadInfo]:
        """Find all threads waiting on a specific lock."""
        return [
            t for t in self.threads
            if t.waiting_on_lock and t.waiting_on_lock.lock_id == lock_id
        ]

    def find_thread_holding_lock(self, lock_id: str) -> Optional[ThreadInfo]:
        """Find the thread holding a specific lock."""
        for thread in self.threads:
            for lock in thread.holding_locks:
                if lock.lock_id == lock_id:
                    return thread
        return None
